const sampleComicBooks = [
  {
    bookName: "Spider-Man: Into the Spider-Verse",
    authorName: "Stan Lee",
    yearOfPublication: 2018,
    price: 19.99,
    discount: 10,
    numberOfPages: 120,
    condition: "New",
    description: "An exciting story of multiple Spider-Men from different universes.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "Batman: The Dark Knight Returns",
    authorName: "Frank Miller",
    yearOfPublication: 1986,
    price: 25.99,
    discount: 5,
    numberOfPages: 224,
    condition: "New",
    description: "A gritty, dystopian story of an older Batman returning to Gotham.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "The Sandman: Preludes & Nocturnes",
    authorName: "Neil Gaiman",
    yearOfPublication: 1989,
    price: 22.99,
    discount: 0,
    numberOfPages: 240,
    condition: "Used",
    description: "The first volume in the critically acclaimed Sandman series.",
    genre: "Fantasy",
    inStock: false
  },
  {
    bookName: "Watchmen",
    authorName: "Alan Moore",
    yearOfPublication: 1987,
    price: 29.99,
    discount: 8,
    numberOfPages: 416,
    condition: "New",
    description: "A deconstruction of the superhero genre, Watchmen explores complex moral issues.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "Maus: A Survivor's Tale",
    authorName: "Art Spiegelman",
    yearOfPublication: 1991,
    price: 15.99,
    discount: 5,
    numberOfPages: 296,
    condition: "Used",
    description: "A graphic novel recounting the horrors of the Holocaust through a powerful story.",
    genre: "Historical",
    inStock: true
  },
  {
    bookName: "V for Vendetta",
    authorName: "Alan Moore",
    yearOfPublication: 1988,
    price: 20.00,
    discount: 15,
    numberOfPages: 296,
    condition: "New",
    description: "A tale of political revolution in a dystopian Britain.",
    genre: "Political Thriller",
    inStock: true
  },
  {
    bookName: "Saga, Vol. 1",
    authorName: "Brian K. Vaughan",
    yearOfPublication: 2012,
    price: 9.99,
    discount: 2,
    numberOfPages: 160,
    condition: "New",
    description: "A science fiction/fantasy series following star-crossed lovers.",
    genre: "Sci-Fi",
    inStock: true
  },
  {
    bookName: "Y: The Last Man, Vol. 1",
    authorName: "Brian K. Vaughan",
    yearOfPublication: 2003,
    price: 14.99,
    discount: 10,
    numberOfPages: 144,
    condition: "New",
    description: "The story of the last surviving man on Earth after a global catastrophe.",
    genre: "Sci-Fi",
    inStock: true
  },
  {
    bookName: "Deadpool: The Good, The Bad, and The Ugly",
    authorName: "Gerry Duggan",
    yearOfPublication: 2013,
    price: 17.99,
    discount: 12,
    numberOfPages: 128,
    condition: "Used",
    description: "Deadpool teams up with Wolverine and Captain America.",
    genre: "Superhero",
    inStock: false
  },
  {
    bookName: "Black Panther: A Nation Under Our Feet",
    authorName: "Ta-Nehisi Coates",
    yearOfPublication: 2016,
    price: 24.99,
    discount: 5,
    numberOfPages: 160,
    condition: "New",
    description: "T'Challa struggles with ruling Wakanda amidst a political uprising.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "Hellboy: Seed of Destruction",
    authorName: "Mike Mignola",
    yearOfPublication: 1994,
    price: 14.00,
    discount: 8,
    numberOfPages: 128,
    condition: "Used",
    description: "Hellboy's first adventure in a world of the supernatural.",
    genre: "Horror",
    inStock: true
  },
  {
    bookName: "Preacher, Vol. 1: Gone to Texas",
    authorName: "Garth Ennis",
    yearOfPublication: 1996,
    price: 19.99,
    discount: 5,
    numberOfPages: 200,
    condition: "New",
    description: "A preacher with divine powers begins a journey to find God.",
    genre: "Adventure",
    inStock: true
  },
  {
    bookName: "The Walking Dead, Vol. 1: Days Gone Bye",
    authorName: "Robert Kirkman",
    yearOfPublication: 2004,
    price: 12.99,
    discount: 10,
    numberOfPages: 144,
    condition: "Used",
    description: "The start of the zombie apocalypse saga.",
    genre: "Horror",
    inStock: false
  },
  {
    bookName: "Ms. Marvel: No Normal",
    authorName: "G. Willow Wilson",
    yearOfPublication: 2014,
    price: 16.99,
    discount: 6,
    numberOfPages: 120,
    condition: "New",
    description: "Kamala Khan's introduction as the new Ms. Marvel.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "X-Men: Days of Future Past",
    authorName: "Chris Claremont",
    yearOfPublication: 1981,
    price: 18.99,
    discount: 7,
    numberOfPages: 144,
    condition: "New",
    description: "A dystopian future where mutants are hunted by Sentinels.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "The Flash: Born to Run",
    authorName: "Mark Waid",
    yearOfPublication: 1992,
    price: 14.99,
    discount: 5,
    numberOfPages: 144,
    condition: "New",
    description: "The origin story of Wally West, the fastest man alive.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "Justice League: Origin",
    authorName: "Geoff Johns",
    yearOfPublication: 2011,
    price: 19.99,
    discount: 10,
    numberOfPages: 192,
    condition: "New",
    description: "The formation of the Justice League to stop an alien invasion.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "Thor: God of Thunder, Vol. 1",
    authorName: "Jason Aaron",
    yearOfPublication: 2013,
    price: 21.99,
    discount: 8,
    numberOfPages: 136,
    condition: "New",
    description: "Thor faces an ancient god killer across time.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "Invincible, Vol. 1: Family Matters",
    authorName: "Robert Kirkman",
    yearOfPublication: 2003,
    price: 16.99,
    discount: 7,
    numberOfPages: 120,
    condition: "New",
    description: "The story of Mark Grayson, a young superhero.",
    genre: "Superhero",
    inStock: true
  },
  {
    bookName: "Green Lantern: Rebirth",
    authorName: "Geoff Johns",
    yearOfPublication: 2005,
    price: 17.99,
    discount: 9,
    numberOfPages: 160,
    condition: "New",
    description: "Hal Jordan returns as the Green Lantern of Earth.",
    genre: "Superhero",
    inStock: true
  }
];
  module.exports = { data: sampleComicBooks };